"use client"

import React, { useState } from "react";
import { ArrowRight, Upload, Bot, Edit, Check, Loader2, FileText, Download, RefreshCw, Sparkles, Target, Trophy } from 'lucide-react';
import { jsPDF } from 'jspdf';

export default function CVUpload() {
  const [cvFile, setCvFile] = useState(null);
  const [cvText, setCvText] = useState("");
  const [script, setScript] = useState(null);
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState("");
  const [uploadStatus, setUploadStatus] = useState("idle"); // idle, uploading, success

  // Handle File Upload
  const handleFileUpload = async (event) => {
    const file = event.target.files[0];
    if (file) {
      setUploadStatus("uploading");
      setCvFile(file);
      setError("");
      
      const reader = new FileReader();
      reader.onload = (e) => {
        setCvText(e.target.result);
        setUploadStatus("success");
      };
      reader.onerror = () => {
        setError("Failed to read file. Please try again.");
        setUploadStatus("idle");
      };
      reader.readAsText(file);
    }
  };

  // Handle drag events
  const handleDragOver = (e) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      setCvFile(file);
      setError("");
      setUploadStatus("uploading");
      
      const reader = new FileReader();
      reader.onload = (e) => {
        setCvText(e.target.result);
        setUploadStatus("success");
      };
      reader.onerror = () => {
        setError("Failed to read file. Please try again.");
        setUploadStatus("idle");
      };
      reader.readAsText(file);
    }
  };

  // Handle Script Generation
  const generateScript = async () => {
    if (!cvFile) {
      setError("Please upload a resume.");
      return;
    }
    setLoading(true);
    setError("");

    try {
      const formData = new FormData();
      formData.append("file", cvFile);

      const response = await fetch("http://localhost:8000/generate_script/", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();
      if (data.error) {
        setError(data.error);
      } else {
        setScript(data.script);
      }
    } catch (err) {
      setError("Failed to generate script. Please try again.");
    }

    setLoading(false);
  };

  // Handle PDF Download
  const handleDownload = async () => {
    if (!script) return;

    try {
      setDownloading(true);

      // Create new PDF document
      const doc = new jsPDF();
      
      // Set font styles
      doc.setFont("helvetica", "bold");
      doc.setFontSize(20);
      
      // Add title
      doc.text("AI-Generated Introduction Script", 20, 20);
      
      // Add generation date
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
      
      // Add horizontal line
      doc.setLineWidth(0.5);
      doc.line(20, 35, 190, 35);
      
      // Function to add a section with title and content
      const addSection = (title, content, yPosition) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text(title, 20, yPosition);
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(12);
        
        // Split text into lines that fit the page width
        const lines = doc.splitTextToSize(content, 170);
        doc.text(lines, 20, yPosition + 10);
        
        return yPosition + 10 + (lines.length * 7); // Return the new Y position
      };
      
      // Add each section
      let yPos = 45;
      yPos = addSection("Personalized Introduction", script.personalized_intro, yPos);
      yPos = addSection("Normal Introduction", script.normal_intro, yPos + 15);
      yPos = addSection("Overall Feedback", script.overall_feedback, yPos + 15);
      
      // Add footer
      doc.setFontSize(10);
      doc.setTextColor(128);
      doc.text("Generated by AI Introduction Generator", 20, 280);
      
      // Save the PDF
      doc.save("ai-introduction-script.pdf");
      
      setDownloading(false);
    } catch (err) {
      setError("Failed to generate PDF. Please try again.");
      setDownloading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-800 to-slate-900 flex flex-col">
      <main className="flex-1">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
          {/* Hero Section */}
          <div className="text-center mb-16">
            <h1 className="text-4xl font-bold mb-5 mt-20 bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-teal-400">
              AI-Powered Introduction Generator
            </h1>
            <p className="text-slate-300 text-lg max-w-3xl mx-auto -mb-5">
              Transform your resume into a compelling self-introduction in seconds
            </p>
          </div>

          {/* Process Steps */}
          <div className="flex flex-wrap justify-center items-center gap-6 mb-12">
            {[
              { icon: Upload, text: "Upload Resume", description: "Upload your CV or resume" },
              { icon: Bot, text: "AI Processing", description: "Our AI analyzes your experience" },
              { icon: Edit, text: "Edit Script", description: "Customize your introduction" },
            ].map((step, index) => (
              <div key={step.text} className="flex flex-col items-center">
                <div className="flex items-center">
                  <div className="w-12 h-12 rounded-full bg-slate-700 flex items-center justify-center shadow-md border border-slate-600">
                    <step.icon className="w-6 h-6 text-teal-400" />
                  </div>
                  <span className="ml-3 font-medium text-slate-200">{step.text}</span>
                  {index < 2 && <ArrowRight className="w-5 h-5 text-slate-400 mx-4 hidden md:block" />}
                </div>
                <p className="text-sm text-slate-400 mt-2">{step.description}</p>
              </div>
            ))}
          </div>

          {/* Upload and Preview Section */}
          <div className="grid md:grid-cols-2 gap-8">
            {/* Upload Area */}
            <div
              className={`p-8 border-2 rounded-xl transition-all duration-300 ${
                uploadStatus === "success"
                  ? "border-teal-400 bg-slate-700/50"
                  : "border-dashed border-slate-600 hover:border-teal-400 bg-slate-800/50"
              }`}
              onDragOver={handleDragOver}
              onDrop={handleDrop}
            >
              <div className="text-center">
                {uploadStatus === "success" ? (
                  <div className="animate-fade-in">
                    <div className="w-16 h-16 bg-slate-700 rounded-full flex items-center justify-center mx-auto mb-4 border border-teal-400">
                      <FileText className="w-8 h-8 text-teal-400" />
                    </div>
                    <h3 className="text-xl font-semibold mb-2 text-teal-300">Resume Uploaded Successfully!</h3>
                    <p className="text-slate-300 mb-4">
                      {cvFile?.name} ({(cvFile?.size / 1024).toFixed(1)} KB)
                    </p>
                    <button
                      onClick={() => {
                        setCvFile(null)
                        setCvText("")
                        setUploadStatus("idle")
                      }}
                      className="px-4 py-2 bg-slate-700 border border-slate-600 rounded-lg text-slate-300 hover:bg-slate-600 transition-colors inline-flex items-center gap-2"
                    >
                      <RefreshCw className="w-4 h-4" />
                      Upload Different File
                    </button>
                  </div>
                ) : uploadStatus === "uploading" ? (
                  <div>
                    <Loader2 className="w-16 h-16 text-teal-400 mx-auto mb-4 animate-spin" />
                    <h3 className="text-xl font-semibold mb-2 text-slate-200">Processing Your Resume...</h3>
                    <p className="text-slate-400 mb-4">This will only take a moment</p>
                  </div>
                ) : (
                  <>
                    <Upload className="w-16 h-16 text-teal-400 mx-auto mb-4" />
                    <h3 className="text-xl font-semibold mb-2 text-slate-200">Upload Your Resume</h3>
                    <p className="text-slate-400 mb-6">Drag & drop your resume file here, or click to browse</p>
                    <input
                      type="file"
                      accept=".pdf,.docx,.txt"
                      className="hidden"
                      id="resume-upload"
                      onChange={handleFileUpload}
                    />
                    <label
                      htmlFor="resume-upload"
                      className="cursor-pointer px-6 py-3 bg-teal-500 text-white rounded-lg inline-block shadow-md hover:bg-teal-600 transition-colors"
                    >
                      Browse Files
                    </label>
                    <p className="text-sm text-slate-500 mt-6">Supported formats: PDF, DOCX, TXT (Max 10MB)</p>
                  </>
                )}
              </div>
            </div>

            {/* Preview Area */}
            <div className="p-8 bg-slate-800 rounded-xl shadow-lg border border-slate-700">
              <h3 className="text-xl font-semibold mb-4 flex items-center text-slate-200">
                <span className="bg-slate-700 w-8 h-8 rounded-full flex items-center justify-center mr-2 border border-slate-600">
                  <Bot className="w-4 h-4 text-teal-400" />
                </span>
                Your AI-Generated Script
              </h3>

              {error && (
                <div className="p-4 bg-red-900/30 border border-red-700 rounded-lg mb-4 text-red-300 text-sm">{error}</div>
              )}

              {loading ? (
                <div className="flex flex-col items-center justify-center py-12">
                  <Loader2 className="w-10 h-10 animate-spin text-teal-400 mb-4" />
                  <p className="text-slate-400">Generating your professional introduction...</p>
                </div>
              ) : script ? (
                <div className="space-y-6 animate-fade-in">
                  <div className="p-4 bg-slate-700/50 rounded-lg border border-slate-600">
                    <h4 className="font-semibold text-slate-200 mb-2 flex items-center">
                      <span className="bg-slate-600 w-6 h-6 rounded-full flex items-center justify-center mr-2">
                        <span className="text-teal-300 text-xs">1</span>
                      </span>
                      Personalized Introduction
                    </h4>
                    <p className="text-slate-300">{script.personalized_intro}</p>
                  </div>

                  <div className="p-4 bg-slate-700/50 rounded-lg border border-slate-600">
                    <h4 className="font-semibold text-slate-200 mb-2 flex items-center">
                      <span className="bg-slate-600 w-6 h-6 rounded-full flex items-center justify-center mr-2">
                        <span className="text-teal-300 text-xs">2</span>
                      </span>
                      Normal Introduction
                    </h4>
                    <p className="text-slate-300">{script.normal_intro}</p>
                  </div>

                  <div className="p-4 bg-slate-700/50 rounded-lg border border-slate-600">
                    <h4 className="font-semibold text-slate-200 mb-2 flex items-center">
                      <span className="bg-slate-600 w-6 h-6 rounded-full flex items-center justify-center mr-2">
                        <span className="text-teal-300 text-xs">3</span>
                      </span>
                      Overall Feedback
                    </h4>
                    <p className="text-slate-300">{script.overall_feedback}</p>
                  </div>
                </div>
              ) : (
                <div className="py-4 text-center text-slate-400">
                  <p className="mb-4">Your professional introduction will appear here after processing.</p>
                  <div className="w-full h-32 bg-slate-700 rounded-lg animate-pulse"></div>
                </div>
              )}

              <div className="flex justify-between items-center mt-8">
                <span className="text-slate-400 text-sm">
                  {script ? `${script.personalized_intro.split(" ").length} words` : "0 words"}
                </span>
                <div className="space-x-3">
                  {script && (
                    <button 
                      onClick={handleDownload}
                      disabled={downloading}
                      className={`px-4 py-2 border border-slate-600 rounded-lg transition-colors inline-flex items-center gap-2 ${
                        downloading 
                          ? 'bg-slate-700 cursor-not-allowed text-slate-400' 
                          : 'hover:bg-slate-700 hover:border-slate-500 text-slate-300'
                      }`}
                    >
                      {downloading ? (
                        <>
                          <Loader2 className="w-4 h-4 animate-spin" />
                          Preparing PDF...
                        </>
                      ) : (
                        <>
                          <Download className="w-4 h-4" />
                          Download PDF
                        </>
                      )}
                    </button>
                  )}
                  <button
                    className={`px-6 py-2 bg-teal-500 text-white rounded-lg shadow-md hover:bg-teal-600 transition-colors inline-flex items-center gap-2 ${
                      !cvText && "opacity-50 cursor-not-allowed"
                    }`}
                    onClick={generateScript}
                    disabled={!cvText || loading}
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <RefreshCw className="w-4 h-4" />
                        Generate Script
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>

          {/* Tips Section */}
          <TipsSection />
        </div>
      </main>

      {downloading && (
        <div className="fixed bottom-4 right-4 bg-slate-800 shadow-lg rounded-lg p-4 flex items-center gap-3 border border-slate-700 animate-fade-in">
          <Loader2 className="w-5 h-5 text-teal-400 animate-spin" />
          <span className="text-slate-300">Preparing your PDF...</span>
        </div>
      )}

      {/* Add some custom CSS for animations */}
      <style jsx>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fadeIn 0.5s ease-out forwards;
        }
        .animate-pulse {
          animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
      `}</style>
    </div>
  );
}

function TipsSection() {
  const tips = [
    {
      icon: Sparkles,
      tip: "Ensure your resume is up-to-date",
      description: "Include your most recent experiences and skills for the best results",
      color: "from-teal-500/10 to-cyan-600/10",
      iconColor: "text-teal-400",
      hoverColor: "hover:from-teal-500/20 hover:to-cyan-600/20",
    },
    {
      icon: Target,
      tip: "Include relevant skills and experiences",
      description: "Focus on skills and experiences that are relevant to your target position",
      color: "from-purple-500/10 to-indigo-600/10",
      iconColor: "text-purple-400",
      hoverColor: "hover:from-purple-500/20 hover:to-indigo-600/20",
    },
    {
      icon: Trophy,
      tip: "Highlight key achievements",
      description: "Quantify your achievements with numbers and metrics when possible",
      color: "from-emerald-500/10 to-teal-600/10",
      iconColor: "text-emerald-400",
      hoverColor: "hover:from-emerald-500/20 hover:to-teal-600/20",
    },
  ];

  return (
    <div className="mt-12 p-8 bg-slate-800 rounded-2xl shadow-xl relative overflow-hidden border border-slate-700">
      {/* Background Pattern */}
      <div className="absolute inset-0 bg-gradient-to-r from-slate-700/50 to-slate-800/50 opacity-50" />
      <div className="absolute inset-0 bg-[linear-gradient(30deg,_transparent_40%,_#1e293b_70%)]" />

      {/* Content */}
      <div className="relative">
        <h3 className="font-semibold text-2xl mb-8 flex items-center text-slate-200">
          <span className="bg-gradient-to-r from-slate-700 to-slate-600 w-10 h-10 rounded-xl flex items-center justify-center mr-3 shadow-inner border border-slate-600">
            <Sparkles className="w-5 h-5 text-teal-400" />
          </span>
          Tips for Better Results
        </h3>

        <div className="grid md:grid-cols-3 gap-6">
          {tips.map((item, index) => (
            <div key={item.tip} className="group relative">
              {/* Card */}
              <div
                className={`
                h-full p-6 rounded-xl transition-all duration-300
                bg-gradient-to-br ${item.color} ${item.hoverColor}
                border border-slate-700 backdrop-blur-sm
                hover:shadow-lg hover:scale-[1.02]
              `}
              >
                {/* Icon */}
                <div className="mb-4">
                  <div
                    className={`
                    w-12 h-12 rounded-xl
                    bg-slate-700 shadow-sm border border-slate-600
                    flex items-center justify-center
                    group-hover:scale-110 transition-transform duration-300
                  `}
                  >
                    <item.icon className={`w-6 h-6 ${item.iconColor}`} />
                  </div>
                </div>

                {/* Content */}
                <h4 className="font-semibold text-slate-200 text-lg mb-2 group-hover:text-slate-100">{item.tip}</h4>
                <p className="text-slate-400 group-hover:text-slate-300">{item.description}</p>

                {/* Learn More Link */}
                <div className="mt-4 flex items-center text-sm font-medium text-slate-400 group-hover:text-slate-200">
                  <span className="mr-2">Learn more</span>
                  <ArrowRight className="w-4 h-4 transform group-hover:translate-x-1 transition-transform" />
                </div>
              </div>

              {/* Number Badge */}
              <div
                className={`
                absolute -top-2 -right-2
                w-8 h-8 rounded-full
                bg-slate-700 shadow-md border border-slate-600
                flex items-center justify-center
                text-sm font-semibold ${item.iconColor}
                group-hover:scale-110 transition-transform duration-300
              `}
              >
                {index + 1}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}